# Home Assistant é…ç½®ï¼šæ–‘é¸ è¯†åˆ«ç³»ç»Ÿ
# å°†æ­¤é…ç½®æ·»åŠ åˆ°ä½ çš„ configuration.yaml æˆ–ä½œä¸ºç‹¬ç«‹åŒ…

# ========== ä¼ æ„Ÿå™¨å®šä¹‰ ==========
sensor:
  # æŽ¥æ”¶ ESP32 å‘é€çš„æ–‘é¸ æ£€æµ‹äº‹ä»¶ï¼ˆé€šè¿‡ REST APIï¼‰
  - platform: rest
    name: "Dove Detection Events"
    resource: http://localhost:8123/api/webhook/dove_detector
    method: POST
    value_template: "{{ value_json.confidence }}"
    json_attributes:
      - device_id
      - event_type
      - confidence
      - timestamp
      - local_time
    scan_interval: 60

# ========== è¾“å…¥è¾…åŠ© ==========
input_number:
  dove_detection_threshold:
    name: "æ–‘é¸ æ£€æµ‹ç½®ä¿¡åº¦é˜ˆå€¼"
    min: 0
    max: 1
    step: 0.01
    initial: 0.7
    unit_of_measurement: "æ¦‚çŽ‡"

input_datetime:
  last_dove_detection:
    name: "æœ€åŽæ£€æµ‹æ—¶é—´"
    has_date: true
    has_time: true

# ========== è®¡æ•°å™¨ ==========
counter:
  dove_count_today:
    name: "ä»Šæ—¥æ–‘é¸ å«å£°æ¬¡æ•°"
    initial: 0
    step: 1
    icon: mdi:bird

  dove_count_week:
    name: "æœ¬å‘¨æ–‘é¸ å«å£°æ¬¡æ•°"
    initial: 0
    step: 1

  dove_count_month:
    name: "æœ¬æœˆæ–‘é¸ å«å£°æ¬¡æ•°"
    initial: 0
    step: 1

# ========== åŽ†å²è®°å½• ==========
recorder:
  include:
    entities:
      - counter.dove_count_today
      - counter.dove_count_week
      - counter.dove_count_month
      - sensor.dove_detection_events

# ========== è‡ªåŠ¨åŒ–ï¼šæŽ¥æ”¶ ESP32 äº‹ä»¶ ==========
automation:
  # æŽ¥æ”¶ ESP32 å‘é€çš„æ£€æµ‹äº‹ä»¶
  - alias: "æŽ¥æ”¶æ–‘é¸ æ£€æµ‹äº‹ä»¶"
    id: receive_dove_detection
    trigger:
      - platform: webhook
        webhook_id: dove_detector
    condition:
      - condition: template
        value_template: "{{ trigger.json.event_type == 'dove_detected' }}"
      - condition: template
        value_template: "{{ trigger.json.confidence | float >= states('input_number.dove_detection_threshold') | float }}"
    action:
      # æ›´æ–°æœ€åŽæ£€æµ‹æ—¶é—´
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_dove_detection
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      
      # å¢žåŠ è®¡æ•°å™¨
      - service: counter.increment
        target:
          entity_id: counter.dove_count_today
      
      # è®°å½•åˆ°æ—¥å¿—
      - service: system_log.write
        data:
          message: "æ£€æµ‹åˆ°æ–‘é¸ å«å£° - ç½®ä¿¡åº¦: {{ trigger.json.confidence | float * 100 | round(1) }}%"
          level: info
      
      # å¯é€‰ï¼šå‘é€é€šçŸ¥
      # - service: notify.mobile_app_your_phone
      #   data:
      #     title: "ðŸ¦ æ£€æµ‹åˆ°æ–‘é¸ å«å£°"
      #     message: "ç½®ä¿¡åº¦: {{ trigger.json.confidence | float * 100 | round(1) }}%"

  # æ¯æ—¥å‡Œæ™¨é‡ç½®è®¡æ•°å™¨
  - alias: "æ¯æ—¥é‡ç½®è®¡æ•°å™¨"
    id: reset_daily_counter
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: counter.reset
        target:
          entity_id: counter.dove_count_today
      
      # å°†ä»Šæ—¥è®¡æ•°ç´¯åŠ åˆ°å‘¨è®¡æ•°
      - service: counter.increment
        target:
          entity_id: counter.dove_count_week
        data:
          value: "{{ states('counter.dove_count_today') | int }}"

  # æ¯å‘¨ä¸€é‡ç½®å‘¨è®¡æ•°å™¨
  - alias: "æ¯å‘¨é‡ç½®è®¡æ•°å™¨"
    id: reset_weekly_counter
    trigger:
      - platform: time
        at: "00:00:00"
        day_of_week:
          - mon
    action:
      - service: counter.reset
        target:
          entity_id: counter.dove_count_week
      
      # å°†å‘¨è®¡æ•°ç´¯åŠ åˆ°æœˆè®¡æ•°
      - service: counter.increment
        target:
          entity_id: counter.dove_count_month
        data:
          value: "{{ states('counter.dove_count_week') | int }}"

  # æ¯æœˆ1å·é‡ç½®æœˆè®¡æ•°å™¨
  - alias: "æ¯æœˆé‡ç½®è®¡æ•°å™¨"
    id: reset_monthly_counter
    trigger:
      - platform: time
        at: "00:00:00"
        day_of_month: 1
    action:
      - service: counter.reset
        target:
          entity_id: counter.dove_count_month

# ========== Webhook é…ç½® ==========
# åœ¨ Home Assistant ä¸­ï¼Œwebhook éœ€è¦åœ¨ configuration.yaml ä¸­é…ç½®
# æˆ–è€…é€šè¿‡ UI: è®¾ç½® -> è®¾å¤‡ä¸ŽæœåŠ¡ -> Webhook -> æ·»åŠ  Webhook
# Webhook ID: dove_detector

